  apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: web-ui
        image: image: 208295046981.dkr.ecr.us-east-2.amazonaws.com/web-ui:v2
        ports:
        - containerPort: 80
